// <auto-generated />
namespace UniversityCourseResultManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Vershion6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vershion6));
        
        string IMigrationMetadata.Id
        {
            get { return "201912181925096_Vershion 6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
